# DO NOT CHANGE the "init" and "install" sections below

environment:
  matrix:
  - Rversion: R
  
  - Rversion: R-stable

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/calbertsen/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

before_build:
  #- cd
  #- ls
  #- git clone -q --branch=cran-version3 https://github.com/kaskr/adcomp.git "C:\projects\TMB"
  #- travis-tool.sh install_devtools
  #- cd C:\projects\TMB\
  # - git show origin/cppad-20140612:TMB/inst/include/cppad/local/pod_vector.hpp > TMB/inst/include/cppad/local/pod_vector.hpp
  # - cd TMB\inst\include\cppad\local\
  # - findstr /v /c:"template <> inline bool is_pod<size_t>(void)" pod_vector.hpp > pod_vector2.hpp
  # - del pod_vector.hpp
  # - move pod_vector2.hpp pod_vector.hpp
  # - type pod_vector.hpp
  # - cd C:\projects\TMB\
  #- R CMD BATCH install_windows.R out.Rout
  #- ls
  #- type out.Rout
  #- make install
  #- cd C:\projects\argostrack\
  #- ls


build_script:
  # - travis-tool.sh install_github kaskr/adcomp/TMB
  - travis-tool.sh install_r TMB
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
